### ISSUE TITLE
The mechanism for setting the default origin is obscure

### ISSUE THREAD

**Issue by pylaligand** [domokit/devtools#62]
See the bottom of https://github.com/domokit/devtools/blob/master/docs/mojo_run.md

Instead of relying on a named file somewhere in the ancestry of the mojo_run file, why not be more explicit and for example allow the Mojo commit # to be passed to the script?
Better yet, how about versioning the devtools and tie them to a certain version of Mojo?

**Comment by ppiet** [comment]
Not sure about versioning the devtools - I think we should either make them actually part of the SDK as discussed in https://github.com/domokit/devtools/issues/61 (in which case they would be tied to particular version of mojo), or keep them separate and flexible with regard to mojo version.

As for allowing a Mojo commit to be passed instead of --origin, that sg.

**Comment by pylaligand** [comment]
Agreed on versioning.
