### ISSUE TITLE
Make mojo_run aware of mojo_sdk's prebuilt shells

### ISSUE THREAD

**Issue by pylaligand** [domokit/devtools#63]
mojo_run needs a shell to work, and mojo_sdk provides a way to use prebuilt binaries downloaded from the cloud.

Currently this is supposed to work without user intervention with the following:
- some file in the mojo_sdk tree copies the prebuilts into the out/ directory of the parent project (https://github.com/domokit/mojo/blob/a5c0426375deca641eb2251800f9ef827b565ded/mojo/public/tools/BUILD.gn)
- mojo_run magically infers the location of these copied prebuilts at https://github.com/domokit/devtools/blob/master/devtoolslib/paths.py#L40

This all goes out of the window if the parent project does not use gn.

**Comment by ppiet** [comment]
Yes, absolutely! We have been thinking about this back then: https://groups.google.com/a/chromium.org/forum/#!topicsearchin/mojo-dev/mojo_use_prebuilt_mojo_shell/mojo-dev/vMjU-gx5eAM , and didn't pursue it only because no-one was asking for it at the time.

If this is useful for you, I'm happy to look into this.

**Comment by pylaligand** [comment]
Yeah it's definitely useful. I managed to make it all work by copying the binaries myself and adding a MOJO_VERSION file, but it would be significantly better if it all worked without any additional setup - other than downloading the binaries, that is.

**Comment by ppiet** [comment]
Proposed patch in review at https://codereview.chromium.org/1844943004/ .
